### ISSUE TITLE
Sass files name

### ISSUE THREAD

**Issue by roukmoute** [MartialGeek/open-cloud-seedbox#6]
Name your partials sass with underscore.
It's best practice :wink: 

http://sass-lang.com/guide on section `Partials`

**Comment by MartialGeek** [comment]
Hi @roukmoute !
Yes I know, what file are you talking about (and in which branch)?

**Comment by roukmoute** [comment]
https://github.com/MartialGeek/open-cloud-seedbox/commit/88799eb47323945a3e3ad44c9baa407f25f588f3

**Comment by MartialGeek** [comment]
The partial you are talking about is prefixed by an underscore: web/src/stylesheets/components/_card.scss

The `@import` statement takes the file name without the underscore.

**Comment by roukmoute** [comment]
Correct !
